name: RankManager
main: Rank\Main
version: 1.0.0
api: 5.0.0
commands:
  rank:
    description: Gérer les grades (create, list, set, addperm)
    usage: "/rank create <grade> | /rank list | /rank set <grade> <joueur> | /rank addperm <grade> <permission>"
    permission: rank.admin
  ranktime:
    description: Attribuer un grade temporaire
    usage: "/ranktime set <grade> <joueur> <durée ex: 1d2h30m>"
    permission: rank.admin
  rankremove:
    description: Retirer le grade d'un joueur (défaut)
    usage: "/rankremove <joueur>"
    permission: rank.admin
permissions:
  rank.admin:
    default: op
